[package]
name = "rf-api-resources"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
thiserror = "1.0"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }

# [[example]]
# name = "basic_usage_rf_api_resources"
# path = "examples/basic_usage.rs"

[package.metadata.rustforge]
tier = "beta"
