//! Mail system commands

use anyhow::{Context, Result};
use colored::*;
use handlebars::Handlebars;
use inflector::Inflector;
use serde_json::json;
use std::fs;
use std::path::Path;

use super::ensure_forge_project;

/// Generate a new Mailable class
///
/// # Example
///
/// ```bash
/// forge make:mail WelcomeEmail
/// forge make:mail order/OrderShippedNotification
/// ```
pub async fn make_mail(name: &str, markdown: bool) -> Result<()> {
    ensure_forge_project()?;

    println!(
        "{}",
        format!("Generating mailable: {}", name).green().bold()
    );

    let mail_name = name.to_pascal_case();
    let mail_path = if name.contains('/') {
        // Nested path (e.g., order/OrderShippedNotification)
        let parts: Vec<&str> = name.split('/').collect();
        let dir = parts[..parts.len() - 1].join("/").to_snake_case();
        let file = parts.last().unwrap().to_snake_case();
        format!("src/mail/{}/{}.rs", dir, file)
    } else {
        format!("src/mail/{}.rs", name.to_snake_case())
    };

    if Path::new(&mail_path).exists() {
        anyhow::bail!("Mailable already exists: {}", mail_path);
    }

    let mail_content = if markdown {
        generate_markdown_mail_content(&mail_name)?
    } else {
        generate_html_mail_content(&mail_name)?
    };

    // Ensure mail directory exists
    if let Some(parent) = Path::new(&mail_path).parent() {
        fs::create_dir_all(parent)?;
    }

    fs::write(&mail_path, mail_content)?;

    println!("  {} Created: {}", "✓".green(), mail_path);

    // Update src/mail/mod.rs
    update_mail_mod(&name.to_snake_case(), &mail_name)?;

    println!();
    println!("{}", "Mailable generated successfully!".green().bold());
    println!();
    println!("Next steps:");
    println!("  1. Customize the mail content in the build() method");
    println!("  2. Send: {}::new(...).send(&mailer).await?", mail_name);
    if cfg!(feature = "queue") {
        println!("  3. Or queue: {}::new(...).queue().await?", mail_name);
    }

    Ok(())
}

fn generate_html_mail_content(mail_name: &str) -> Result<String> {
    let template = r##"use rf_mail::prelude::*;

/// {{mail_name}} email
#[derive(Debug, Clone)]
pub struct {{mail_name}} {
    pub to: String,
    // Add your fields here
}

impl Mailable for {{mail_name}} {
    fn build(&self) -> MailBuilder {
        MailBuilder::new()
            .from(Address::new("noreply@example.com"))
            .to(Address::new(&self.to))
            .subject("Your Subject Here")
            .html(r#"
                <!DOCTYPE html>
                <html>
                <head>
                    <title>{{mail_name}}</title>
                </head>
                <body>
                    <h1>Hello!</h1>
                    <p>This is a mail generated by RustForge.</p>
                </body>
                </html>
            "#)
            .text("Hello! This is a plain text version.")
            .build()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rf_mail::testing::{fake, assert_sent, restore};

    #[tokio::test]
    async fn test_send_{{snake_name}}() {
        let fake_mailer = fake();

        let mail = {{mail_name}} {
            to: "test@example.com".into(),
        };

        mail.send(&*fake_mailer).await.unwrap();

        assert_sent(|msg| msg.to[0].email == "test@example.com");

        restore();
    }
}
"##;

    let mut handlebars = Handlebars::new();
    handlebars.register_template_string("mail", template)?;

    let data = json!({
        "mail_name": mail_name,
        "snake_name": mail_name.to_snake_case(),
    });

    Ok(handlebars.render("mail", &data)?)
}

fn generate_markdown_mail_content(mail_name: &str) -> Result<String> {
    let template = r##"use rf_mail::prelude::*;

/// {{mail_name}} email
#[derive(Debug, Clone)]
pub struct {{mail_name}} {
    pub to: String,
    pub name: String,
    // Add your fields here
}

impl Mailable for {{mail_name}} {
    fn build(&self) -> MailBuilder {
        let markdown = format!(
            r#"# Hello, {{{{name}}}}!

This is a markdown email with components.

@panel
**Important:** This is a highlighted panel with important information.
@endpanel

@button(https://example.com)
Click This Button
@endbutton

## Details

Here you can add more content with **bold** and *italic* text.

@table
| Column 1 | Column 2 | Column 3 |
|----------|----------|----------|
| Value 1  | Value 2  | Value 3  |
| Value 4  | Value 5  | Value 6  |
@endtable

---

Best regards,
The Team
"#,
            name = self.name,
        );

        MailBuilder::new()
            .from(Address::with_name("noreply@example.com", "Your App"))
            .to(Address::new(&self.to))
            .subject("{{mail_name}}")
            .markdown(markdown)
            .build()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rf_mail::testing::{fake, assert_sent, restore};

    #[tokio::test]
    async fn test_send_{{snake_name}}() {
        let fake_mailer = fake();

        let mail = {{mail_name}} {
            to: "test@example.com".into(),
            name: "Alice".into(),
        };

        mail.send(&*fake_mailer).await.unwrap();

        assert_sent(|msg| {
            msg.to[0].email == "test@example.com" &&
            msg.subject == "{{mail_name}}"
        });

        restore();
    }
}
"##;

    let mut handlebars = Handlebars::new();
    handlebars.register_template_string("mail", template)?;

    let data = json!({
        "mail_name": mail_name,
        "snake_name": mail_name.to_snake_case(),
    });

    Ok(handlebars.render("mail", &data)?)
}

fn update_mail_mod(file_name: &str, mail_name: &str) -> Result<()> {
    let mod_file = "src/mail/mod.rs";

    let mut content = if Path::new(mod_file).exists() {
        fs::read_to_string(mod_file)?
    } else {
        fs::create_dir_all("src/mail")?;
        String::from("//! Mail types\n\n")
    };

    // Handle nested modules
    let (mod_line, use_line) = if file_name.contains('/') {
        let parts: Vec<&str> = file_name.split('/').collect();
        let mod_name = parts[0];
        let submod = parts[1];

        let mod_decl = format!("pub mod {};\n", mod_name);
        let use_stmt = format!("pub use {}::{}::{};\n", mod_name, submod, mail_name);

        (mod_decl, use_stmt)
    } else {
        let mod_line = format!("pub mod {};\n", file_name);
        let use_line = format!("pub use {}::{};\n", file_name, mail_name);
        (mod_line, use_line)
    };

    if !content.contains(&mod_line) {
        content.push_str(&mod_line);
    }

    if !content.contains(&use_line) {
        content.push_str(&use_line);
    }

    fs::write(mod_file, content)?;
    println!("  {} Updated: {}", "✓".green(), mod_file);

    Ok(())
}

/// Test mail sending
///
/// # Example
///
/// ```bash
/// forge mail:test user@example.com
/// forge mail:test user@example.com --subject="Test Email"
/// ```
pub async fn test_mail(to: &str, subject: Option<&str>, markdown: bool) -> Result<()> {
    ensure_forge_project()?;

    println!("{}", "Sending test email...".green().bold());
    println!("  To: {}", to);
    println!(
        "  Subject: {}",
        subject.unwrap_or("Test Email from RustForge")
    );

    // TODO: Load mail config and send actual email
    // For now, just show what would be sent

    println!();
    println!("{}", "Test email would be sent!".green());
    println!();
    println!("To actually send emails, configure your mail driver in config/mail.toml");

    Ok(())
}
