use serde::{Deserialize, Serialize};

/// A single message in a conversation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "role", rename_all = "lowercase")]
pub enum Message {
    /// A system-level instruction that shapes model behaviour.
    System { content: String },
    /// A message sent by the end-user.
    User { content: String },
    /// A message generated by the assistant.
    Assistant { content: String },
}

impl Message {
    /// Create a system message.
    pub fn system(content: impl Into<String>) -> Self {
        Message::System { content: content.into() }
    }

    /// Create a user message.
    pub fn user(content: impl Into<String>) -> Self {
        Message::User { content: content.into() }
    }

    /// Create an assistant message.
    pub fn assistant(content: impl Into<String>) -> Self {
        Message::Assistant { content: content.into() }
    }

    /// Return the text content regardless of role.
    pub fn content(&self) -> &str {
        match self {
            Message::System { content }
            | Message::User { content }
            | Message::Assistant { content } => content.as_str(),
        }
    }
}

/// A request to generate text from an AI model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TextRequest {
    /// The model identifier (e.g. `"claude-3-5-sonnet-20241022"`).
    pub model: String,
    /// The conversation history / prompt.
    pub messages: Vec<Message>,
    /// Sampling temperature in `[0.0, 2.0]`.
    pub temperature: Option<f64>,
    /// Maximum number of tokens to generate.
    pub max_tokens: Option<u32>,
    /// An optional system prompt that is prepended to the conversation.
    pub system: Option<String>,
}

impl TextRequest {
    /// Begin building a `TextRequest`.
    pub fn builder(model: impl Into<String>) -> TextRequestBuilder {
        TextRequestBuilder::new(model)
    }
}

/// Builder for [`TextRequest`].
#[derive(Debug, Default)]
pub struct TextRequestBuilder {
    model: String,
    messages: Vec<Message>,
    temperature: Option<f64>,
    max_tokens: Option<u32>,
    system: Option<String>,
}

impl TextRequestBuilder {
    /// Create a new builder for the given model.
    pub fn new(model: impl Into<String>) -> Self {
        Self { model: model.into(), ..Default::default() }
    }

    /// Append a message to the conversation.
    pub fn message(mut self, msg: Message) -> Self {
        self.messages.push(msg);
        self
    }

    /// Set the sampling temperature.
    pub fn temperature(mut self, t: f64) -> Self {
        self.temperature = Some(t);
        self
    }

    /// Set the maximum number of tokens to generate.
    pub fn max_tokens(mut self, n: u32) -> Self {
        self.max_tokens = Some(n);
        self
    }

    /// Set a system prompt.
    pub fn system(mut self, s: impl Into<String>) -> Self {
        self.system = Some(s.into());
        self
    }

    /// Build the [`TextRequest`].
    pub fn build(self) -> TextRequest {
        TextRequest {
            model: self.model,
            messages: self.messages,
            temperature: self.temperature,
            max_tokens: self.max_tokens,
            system: self.system,
        }
    }
}

/// The response from a text-generation request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TextResponse {
    /// The generated text.
    pub content: String,
    /// The model that produced the response.
    pub model: String,
    /// Number of tokens consumed by the prompt.
    pub prompt_tokens: Option<u32>,
    /// Number of tokens generated.
    pub completion_tokens: Option<u32>,
    /// The reason the model stopped generating.
    pub finish_reason: Option<String>,
}

impl TextResponse {
    /// Create a simple response (useful for testing / mocking).
    pub fn new(content: impl Into<String>, model: impl Into<String>) -> Self {
        Self {
            content: content.into(),
            model: model.into(),
            prompt_tokens: None,
            completion_tokens: None,
            finish_reason: None,
        }
    }
}
